version: "3.8"

#services:
#  db:
#    image: postgres:15
#    container_name: PracticeDB
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin123
#      POSTGRES_DB: practicedb
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    restart: unless-stopped
#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
#    restart: unless-stopped
#volumes:
#  postgres_data:
#    driver: local